name: PDeploy spcae game app #######

on:
  
  push:
    branches:
      - project-1
    paths:
      - 'application-1/**'
      
    
     
env:
  DATABRICKS_HOST: https://adb-5630925069180830.10.azuredatabricks.net
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  DOTNET_INSTALL_DIR: "runner/dotnet"

  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          ref: project-1
          path: muliple-projects-hub/project-1/Application
        
     # - name: .Net Build
      #  uses: EasyDesk/action-dotnet-build@v1.0.0
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '6.0'
    
        
        
     

