name: notebooks 

on:
  
  push:
    branches:
      - project-1
    paths:
      - 'application-1/**'
      
    
     
env:
  DATABRICKS_HOST: https://adb-5076614175371553.13.azuredatabricks.net
  

  

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          #submodules: true
          ref: project-1
          path: application-1
      - name: adad
        uses: antstackio/databricks-deploy@v1.0.2
        with:
          databricks-repo-branch: 'project-1'
          databricks-token: 'dapi0853497e6218536ee19ee744430a2450-3'
          databricks-host: 'https://adb-5076614175371553.13.azuredatabricks.net'
          databricks-repo-id: 'prasadkesari329.dk@outlook.com'
     
        
